name: Merge ABP Filter Lists

on:
  schedule:
    - cron: '0 1 * * *'   # 每天凌晨1点（UTC）
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write
  
jobs:
  merge-abp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # 获取完整历史，以便比较变更

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Directory for Filter Lists
        run: mkdir -p abp-lists

      - name: Download ABP Filter Lists (only if updated)
        run: |
          cd abp-lists
          wget -O https://easylist.to/easylist/easylist.txt
          wget -O https://easylist.to/easylist/easyprivacy.txt
          wget -O https://easylist-downloads.adblockplus.org/easylistchina.txt
          wget -O https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
          wget -O https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt
          wget -O https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
          wget -O https://easylist-downloads.adblockplus.org/v3/full/distraction-control-free.txt
          wget -O https://secure.fanboy.co.nz/fanboy-annoyance.txt
          wget -O https://easylist.to/easylist/fanboy-social.txt
          wget -O https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          wget -O https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt
          wget -O https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
          wget -O https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt

      - name: Merge and Deduplicate Filter Lists
        run: |
          cat abp-lists/*.txt | grep -vE '^\s*$' | awk '!a[$0]++' > merged_abp_filters.txt

      - name: Commit and Push Changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
            git add abp-lists/*.txt merged_abp_filters.txt
            git commit -m "auto: update merged ABP filters $(date +'%F %T')"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
            git push origin HEAD
          else
            echo "No changes to commit."
          fi
