name: Merge ABP Filter Lists

on:
  schedule:
    - cron: '0 1 * * *'   # 每天凌晨1点（UTC）
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write
  
jobs:
  merge-abp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        # fetch-depth 默认 1，不拉取完整历史
        
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Directory for Filter Lists
        run: mkdir -p abp-lists

      - name: Download ABP Filter Lists
        run: |
          cd abp-lists
          wget -O easylist.txt https://easylist.to/easylist/easylist.txt
          wget -O easyprivacy.txt https://easylist.to/easylist/easyprivacy.txt
          wget -O easylistchina.txt https://easylist-downloads.adblockplus.org/easylistchina.txt
          wget -O easylistchina+easylist.txt https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
          wget -O abp-filters-anti-cv.txt https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt
          wget -O antiadblockfilters.txt https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
          wget -O distraction-control-free.txt https://easylist-downloads.adblockplus.org/v3/full/distraction-control-free.txt
          wget -O fanboy-annoyance.txt https://secure.fanboy.co.nz/fanboy-annoyance.txt
          wget -O fanboy-social.txt https://easylist.to/easylist/fanboy-social.txt
          wget -O cjx-annoyance.txt https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          wget -O mv.txt https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt
          wget -O ADgk.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
          wget -O kill-baidu-ad.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt

      - name: Merge and Deduplicate Filter Lists
        run: |
          awk 'NF && !seen[$0]++' abp-lists/*.txt > merged_abp_filters.txt

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Merged ABP Filters
          draft: false
          prerelease: false
          files: merged_abp_filters.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
