name: Merge ABP Filter Lists

on:
  schedule:
    - cron: '0 1 * * *'   # 每天凌晨1点（UTC）
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write
  
jobs:
  merge-abp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        # fetch-depth 默认 1，不拉取完整历史
        
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Directory for Filter Lists
        run: mkdir -p abp-lists

      - name: Download ABP Filter Lists
        run: |
          cd abp-lists
          wget -q --show-progress --tries=3 --timeout=30 -O easylist.txt https://easylist.to/easylist/easylist.txt
          wget -q --show-progress --tries=3 --timeout=30 -O easyprivacy.txt https://easylist.to/easylist/easyprivacy.txt
          wget -q --show-progress --tries=3 --timeout=30 -O easylistchina.txt https://easylist-downloads.adblockplus.org/easylistchina.txt
          wget -q --show-progress --tries=3 --timeout=30 -O easylistchina+easylist.txt https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
          wget -q --show-progress --tries=3 --timeout=30 -O abp-filters-anti-cv.txt https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt
          wget -q --show-progress --tries=3 --timeout=30 -O antiadblockfilters.txt https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
          wget -q --show-progress --tries=3 --timeout=30 -O distraction-control-free.txt https://easylist-downloads.adblockplus.org/v3/full/distraction-control-free.txt
          wget -q --show-progress --tries=3 --timeout=30 -O fanboy-annoyance.txt https://secure.fanboy.co.nz/fanboy-annoyance.txt
          wget -q --show-progress --tries=3 --timeout=30 -O fanboy-social.txt https://easylist.to/easylist/fanboy-social.txt
          wget -q --show-progress --tries=3 --timeout=30 -O cjx-annoyance.txt https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          wget -q --show-progress --tries=3 --timeout=30 -O mv.txt https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt
          wget -q --show-progress --tries=3 --timeout=30 -O ADgk.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
          wget -q --show-progress --tries=3 --timeout=30 -O kill-baidu-ad.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt

      - name: Merge and Deduplicate Filter Lists
        run: |
          awk 'NF && !seen[$0]++' abp-lists/*.txt > merged_abp_filters.txt

      - name: Commit and Push Changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add abp-lists/*.txt merged_abp_filters.txt
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "auto: update merged ABP filters $(date +'%F %T')"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
            git push origin HEAD
