name: Merge ABP Filter Lists

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  merge-abp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Directory for Filter Lists
        run: mkdir -p abp-lists

      - name: Download ABP Filter Lists
        run: |
          cd abp-lists
          wget -O easylist.txt https://easylist.to/easylist/easylist.txt
          wget -O easyprivacy.txt https://easylist.to/easylist/easyprivacy.txt
          wget -O easylistchina.txt https://easylist-downloads.adblockplus.org/easylistchina.txt
          wget -O easylistchina+easylist.txt https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
          wget -O abp-filters-anti-cv.txt https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt
          wget -O antiadblockfilters.txt https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
          wget -O distraction-control-free.txt https://easylist-downloads.adblockplus.org/v3/full/distraction-control-free.txt
          wget -O fanboy-annoyance.txt https://secure.fanboy.co.nz/fanboy-annoyance.txt
          wget -O fanboy-social.txt https://easylist.to/easylist/fanboy-social.txt
          wget -O cjx-annoyance.txt https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          wget -O mv.txt https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt
          wget -O ADgk.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
          wget -O kill-baidu-ad.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt

      - name: Merge and Deduplicate Filter Lists (Fixed Order)
        run: |
          
          OLD_FILE="merged_abp_filters.txt"
          [ -f "$OLD_FILE" ] && cp "$OLD_FILE" old_merged.txt || touch old_merged.txt

          VERSION_DATE=$(date -u +"%Y%m%d%H%M")
          LAST_MODIFIED=$(date -u +"%d %b %Y %H:%M UTC")

          TMP_FILE="merged_rules_tmp.txt"

          cat abp-lists/easylist.txt \
              abp-lists/easyprivacy.txt \
              abp-lists/easylistchina.txt \
              abp-lists/easylistchina+easylist.txt \
              abp-lists/abp-filters-anti-cv.txt \
              abp-lists/antiadblockfilters.txt \
              abp-lists/distraction-control-free.txt \
              abp-lists/fanboy-annoyance.txt \
              abp-lists/fanboy-social.txt \
              abp-lists/cjx-annoyance.txt \
              abp-lists/mv.txt \
              abp-lists/ADgk.txt \
              abp-lists/kill-baidu-ad.txt \
            | awk '
                { sub(/\r$/, "", $0) }
                /^[[:space:]]*$/ { next }
                /^[[:space:]]*!/ { next }
                /^[[:space:]]*\[/ { next }
                { s = $0
                  sub(/^[[:space:]]+/, "", s)
                  sub(/[[:space:]]+$/, "", s)
                }
                !seen[s]++ { print s }
            ' > "$TMP_FILE"

          TOTAL_RULES=$(wc -l < "$TMP_FILE")

          {
            printf "%s\n" "[Adblock Plus 2.0]"
            printf "%s\n" "! Version: %s" "$VERSION_DATE"
            printf "%s\n" "! Title: EasyList"
            printf "%s\n" "! Last modified: %s" "$LAST_MODIFIED"
            printf "%s\n" "! Total rules: %s" "$TOTAL_RULES"
            cat "$TMP_FILE"
          } > merged_abp_filters.txt

          rm -f "$TMP_FILE"

          if cmp -s merged_abp_filters.txt old_merged.txt; then
            echo "Merged file unchanged, skipping commit and release."
            exit 0
          fi

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --quiet abp-lists merged_abp_filters.txt; then
            echo "No changes to commit."
          else
            git add abp-lists/*.txt merged_abp_filters.txt
            git commit -m "auto: update merged ABP filters $(date +'%F %T')"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
            git push origin HEAD
            git tag -f latest
            git push -f origin latest
          fi

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Merged ABP Filters
          draft: false
          prerelease: false
          files: merged_abp_filters.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
