name: test download

on:
  schedule:
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write
  
jobs:
  merge-abp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        # fetch-depth 默认 1，不拉取完整历史
        
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Directory for Filter Lists
        run: mkdir -p abp-lists

      - name: Download ABP Filter Lists
        run: |
          cd abp-lists
          wget -O easylist.txt https://easylist.to/easylist/easylist.txt
